Movie_site/FianlPro/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings



urlpatterns = [
    path('admin/', admin.site.urls),
    path('group/', include(('group.urls', 'group'), namespace='group'), name='group'),
    path('user/', include(('user.urls', 'user'), namespace='user'), name='user'),
    path('movie/', include(('movie.urls', 'movie'), namespace='movie'), name='movie'),
]

Movie_site/group/urls.py
from django.urls import path
from group.views import IndexView, VoteRecordView, EventView, VoteListView, VoteDetailView, GroupCreateView, \
    GroupJoinView, GroupUnsubscribeView, EventCreateview, VoteCreateview


urlpatterns = [
    path('index/', IndexView.as_view(), name='index'),
    path('vote_record/', VoteRecordView.as_view(), name='vote_record'),
    path('event/', EventView.as_view(), name='event'),
    path('vote/', VoteListView.as_view(), name='vote'),
    path('vote_detail/', VoteDetailView.as_view(), name='vote_detail'),
    path('create_group/', GroupCreateView.as_view(), name='create_group'),
    path('join_group/', GroupJoinView.as_view(), name='join_group'),
    path('unsubscribe/', GroupUnsubscribeView.as_view(), name='unsubscribe'),
    path('create_event/', EventCreateview.as_view(), name='create_event'),
    path('create_vote/', VoteCreateview.as_view(), name='create_vote'),

    ]

Movie_site/movie/urls.py
from django.urls import path
from movie.views import ListView,PullMovieView


urlpatterns = [
    path('list/', ListView.as_view(), name='list'),
    path('pull_movie/', PullMovieView.as_view(), name='pull_movie'),
    ]

Movie_site/user/urls.py
from django.urls import path
from user.views import RegisterView,LoginView, LogoutView, UserInfoView

urlpatterns = [
    path('register/', RegisterView.as_view(), name='register'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/',LogoutView.as_view(), name='logout'),
    path('',UserInfoView.as_view(), name='user')
    ]

Movie_site/templates/base.html
{#  Sign-In Sign-Up #}
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
{% load staticfiles %}
<head>
    <meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
    {# Web Content #}
    <title>{% block title %}{% endblock title %}</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/reset.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
    {# Top #}
    {% block topfiles %}{% endblock topfiles %}
</head>
<body>
{# Web Top Block #}
{% block header_con %}
    <div class="header_con">
        <div class="header">
            <div class="welcome fl">Welcome to MyMovieSite!</div>
            <div class="fr">
        {% if user.is_authenticated %}
                    <div class="login_btn fl">
                        Welcome：<em>{{ user.username }}</em>
            <span>|</span>
                    <a href="{% url 'user:login' %}">Logout</a>
                </div>
        {% else %}
                <div class="login_btn fl">
                    <a href="{% url 'user:login' %}">Lougin</a>
                    <span>|</span>
                    <a href="{% url 'user:register' %}">Register</a>
                </div>
        {% endif %}

            </div>
        </div>      
    </div>
{% endblock header_con %}


{# Web Body Block #}
{% block body %}{% endblock body %}

    <div class="footer">
        <div class="foot_link">
            <a href="#">About Us</a>
            <span>|</span>
            <a href="#">TEAM3</a>
            <span>|</span>
            <a href="#">OOD</a>
            <span>|</span>
            <a href="#">Contact</a>        
        </div>
        <p>CopyRight © 2020 Geogre Washtington SEAS All Rights Reserved</p>
        <p>TEL：202-****888    *******8</p>
    </div>
    {# 网页底部html元素块 #}
    {% block bottom %}{% endblock bottom %}
    {# 网页底部引入文件块 #}
    {% block bottomfiles %}{% endblock bottomfiles %}
</body>
</html>

Movie_site/templates/base_detail_list.html
{# detail page/ list page#}
{% extends 'base.html' %}
{# 网站主体内容块 #}
{% block body %}
    <div class="navbar_con">
        <div class="navbar clearfix">
            <div class="subnav_con fl">
                <h1>All Movies</h1>
                <span></span>
                <ul class="subnav">
                    {% for movie in movies %}
                    <li><a href="{% url 'group:index' movie.id 1 %}" class="{{ movie.logo }}">{{ movie.name }}</a></li>
                    {% endfor %}
                </ul>
            </div>
            <ul class="navlist fl">
                <li><a href="{% url 'movie:list' %}">Movie</a></li>
                <li class="interval">|</li>
                <li><a href="{ url 'group:index' }">Group</a></li>
            </ul>
        </div>
    </div>
    {# 详情页，列表页主体内容块 #}
    {% block main_content %}{% endblock main_content %}
{% endblock body %}

Movie_site/templates/create_event.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}MyMovieSite:Register{% endblock title %}
{% block topfiles %}
    <script type="text/javascript" src="{% static 'js/jquery-1.12.4.min.js' %}"></script>
{% endblock topfiles %}
{% block header_con %}{% endblock header_con %}
{% block search_bar %}{% endblock search_bar %}
{% block body %}
    <div class="register_con">
        <div class="l_con fl">
            <div class="reg_slogan">OOD TEAM 3</div>
            <div class="reg_banner"></div>
        </div>

        <div class="r_con fr">
            <div class="reg_title clearfix">
                <h1>Create an Event</h1>
                <a href="{% url 'group:event' %}">Back</a>
            </div>
            <div class="reg_form clearfix">
                <form method="post" action="/group/create_event/">
                    {% csrf_token %}
                <ul>
                    <li>
                        <label>Event:</label>
                        <input type="text" name="event_name" id="event_name">
                    </li>
                    <li>
                        <label>Movie:</label>
                        <input type="text" name="event_movie" id="event_movie">
                    </li>
                    <li>
                        <label>Group:</label>
                        <input type="text" name="event_group" id="event_group">
                    </li>

                    <li class="agreement">
                        <input type="checkbox" name="allow" id="allow" checked="checked">
                        <label>Concent"User Agreement"</label>
                    </li>
                    <li class="reg_sub">
                        <input type="submit" value="Create" name="">
                    </li>
                </ul>
                </form>
                {{ errmsg }}
            </div>

        </div>

    </div>
{% endblock body %}

Movie_site/templates/create_group.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}MyMovieSite:Register{% endblock title %}
{% block topfiles %}
    <script type="text/javascript" src="{% static 'js/jquery-1.12.4.min.js' %}"></script>
{% endblock topfiles %}
{% block header_con %}{% endblock header_con %}
{% block search_bar %}{% endblock search_bar %}
{% block body %}
    <div class="register_con">
        <div class="l_con fl">
            <div class="reg_slogan">OOD TEAM 3</div>
            <div class="reg_banner"></div>
        </div>

        <div class="r_con fr">
            <div class="reg_title clearfix">
                <h1>Create a Group</h1>
                <a href="{% url 'group:index' %}">Back</a>
            </div>
            <div class="reg_form clearfix">
                <form method="post" action="/group/create_group/">
                    {% csrf_token %}
                <ul>

                    <li>
                        <label>Group Name:</label>
                        <input type="text" name="group_name" id="group_name">
                    </li>

                    <li class="agreement">
                        <input type="checkbox" name="allow" id="allow" checked="checked">
                        <label>Concent"User Agreement"</label>
                    </li>
                    <li class="reg_sub">
                        <input type="submit" value="Create" name="">
                    </li>
                </ul>
                </form>
                {{ errmsg }}
            </div>

        </div>

    </div>
{% endblock body %}

Movie_site/templates/create_vote.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}MyMovieSite:Register{% endblock title %}
{% block topfiles %}
    <script type="text/javascript" src="{% static 'js/jquery-1.12.4.min.js' %}"></script>
{% endblock topfiles %}
{% block header_con %}{% endblock header_con %}
{% block search_bar %}{% endblock search_bar %}
{% block body %}
    <div class="register_con">
        <div class="l_con fl">
            <div class="reg_slogan">OOD TEAM 3</div>
            <div class="reg_banner"></div>
        </div>

        <div class="r_con fr">
            <div class="reg_title clearfix">
                <h1>Create a Vote</h1>
                <a href="{% url 'group:vote' %}">Back</a>
            </div>
            <div class="reg_form clearfix">
                <form method="post" action="/group/create_vote/">
                    {% csrf_token %}
                <ul>
                    <li>
                        <label>Vote:</label>
                        <input type="text" name="vote_name" id="vote_name">
                    </li>
                    <li>
                        <label>Movie:</label>
                        <input type="text" name="vote_movie" id="vote_movie">
                    </li>
                    <li>
                        <label>Opendate:</label>
                        <input type="text" name="open_time" id="open_time">
                    </li>
                    <li>
                        <label>Closedate:</label>
                        <input type="text" name="close_time" id="close_time">
                    </li>
                    <li>
                        <label>Event:</label>
                        <input type="text" name="vote_event" id="vote_event">
                    </li>
                    <li class="agreement">
                        <input type="checkbox" name="allow" id="allow" checked="checked">
                        <label>Concent"User Agreement"</label>
                    </li>
                    <li class="reg_sub">
                        <input type="submit" value="Create" name="">
                    </li>
                </ul>
                </form>
                {{ errmsg }}
            </div>

        </div>

    </div>
{% endblock body %}

Movie_site/templates/detail.html
{% extends 'base_detail_list.html' %}
{% load staticfiles %}
{% block title %}悟空商城-商品详情{% endblock title %}

{% block main_content %}
    <div class="breadcrumb">
        <a href="#">全部分类</a>
        <span>></span>
        <a href="#">{{ sku.type.name }}</a>
        <span>></span>
        <a href="#">商品详情</a>
    </div>

    <div class="goods_detail_con clearfix">
        <div class="goods_detail_pic fl"><img src="{{ sku.image.url }}"></div>

        <div class="goods_detail_list fr">
            <h3>{{ sku.name }}</h3>
            <p>{{ sku.desc }}</p>
            <div class="prize_bar">
                <span class="show_pirze">¥<em>{{ sku.price }}</em></span>
                <span class="show_unit">单  位：{{ sku.unite }}</span>
            </div>
            <div class="goods_num clearfix">
                <div class="num_name fl">数 量：</div>
                <div class="num_add fl">
                    <input type="text" class="num_show fl" value="1">
                    <a href="javascript:;" class="add fr">+</a>
                    <a href="javascript:;" class="minus fr">-</a>   
                </div> 
            </div>
            <div>
                <p>其他规格:</p>
                <ul>
                    {% for sku in same_spu_skus %}
                        <li><a href="{% url 'goods:detail' sku.id %}">{{ sku.name }}</a></li>
                    {% endfor %}
                </ul>
            </div>

            <div class="total">总价：<em>16.80元</em></div>
            <div class="operate_btn">
                {% csrf_token %}
                <a href="javascript:;" class="buy_btn">立即购买</a>
                <a href="javascript:;" sku_id="{{ sku.id }}" class="add_cart" id="add_cart">加入购物车</a>
            </div>
        </div>
    </div>

    <div class="main_wrap clearfix">
        <div class="l_wrap fl clearfix">
            <div class="new_goods">
                <h3>新品推荐</h3>
                <ul>
                    {% for sku in new_skus %}
                    <li>
                        <a href="{% url 'goods:detail' sku.id %}"><img src="{{ sku.image.url }}"></a>
                        <h4><a href="{% url 'goods:detail' sku.id %}">{{ sku.name }}</a></h4>
                        <div class="prize">￥{{ sku.price }}</div>
                    </li>
                    {% endfor %}
                </ul>
            </div>
        </div>

        <div class="r_wrap fr clearfix">
            <ul class="detail_tab clearfix">
                <li id='tag_detail' class="active">商品介绍</li>
                <li id="tag_comment">评论</li>
            </ul>

            <div class="tab_content" id="tab_detail">
                <dl>
                    <dt>商品详情：</dt>
                    <dd>{{ sku.goods.detail|safe }}</dd>
                </dl>
            </div>

            <div class="tab_content" id="tab_comment" style="display: none">
                <dl>
                    {% for order in sku_orders %}
                    <dt>评论时间：{{ order.update_time }}&nbsp;&nbsp;用户名:{{ order.order.user.username }}</dt>
                    <dd>评论内容:{{ order.comment }}</dd>
                    {% endfor %}
                </dl>
            </div>
        </div>
    </div>
{% endblock main_content %}
{% block bottom %}
    <div class="add_jump"></div>
{% endblock bottom %}
{% block bottomfiles %}
    <script type="text/javascript" src="{% static 'js/jquery-1.12.4.min.js' %}"></script>
    <script type="text/javascript">
        $('#tag_detail').click(function () {
            $('#tag_comment').removeClass('active')
            $(this).addClass('active')
            $('#tab_detail').show()
            $('#tab_comment').hide()
        })

        $('#tag_comment').click(function () {
            $('#tag_detail').removeClass('active')
            $(this).addClass('active')
            $('#tab_detail').hide()
            $('#tab_comment').show()
        })

        update_goods_amount()
        // 计算商品的总价格
        function update_goods_amount() {
            // 获取商品的单价和数量
            price = $('.show_pirze').children('em').text()
            count = $('.num_show').val()
            // 计算商品的总价
            price = parseFloat(price)
            count = parseInt(count)
            amount = price*count
            // 设置商品的总价
            $('.total').children('em').text(amount.toFixed(2)+'元')
        }

        // 增加商品的数量
        $('.add').click(function () {
            // 获取商品原有的数目
            count = $('.num_show').val()
            // 加1
            count = parseInt(count)+1
            // 重新设置商品的数目
            $('.num_show').val(count)
            // 更新商品的总价
            update_goods_amount()
        })

        // 减少商品的数量
        $('.minus').click(function () {
            // 获取商品原有的数目
            count = $('.num_show').val()
            // 减1
            count = parseInt(count)-1
            if (count <= 0){
                count = 1
            }
            // 重新设置商品的数目
            $('.num_show').val(count)
            // 更新商品的总价
            update_goods_amount()
        })

        // 手动输入商品的数量
        $('.num_show').blur(function () {
            // 获取用户输入的数目
            count = $(this).val()
            // 校验count是否合法
            if (isNaN(count) || count.trim().length==0 || parseInt(count) <=0){
                count = 1
            }
            // 重新设置商品的数目
            $(this).val(parseInt(count))
            // 更新商品的总价
            update_goods_amount()
        })

        // 获取add_cart div元素左上角的坐标
        var $add_x = $('#add_cart').offset().top;
        var $add_y = $('#add_cart').offset().left;

        // 获取show_count div元素左上角的坐标
        var $to_x = $('#show_count').offset().top;
        var $to_y = $('#show_count').offset().left;


        $('#add_cart').click(function(){
            // 获取商品id和商品数量
            sku_id = $(this).attr('sku_id') // attr prop
            count = $('.num_show').val()
            csrf = $('input[name="csrfmiddlewaretoken"]').val()
            // 组织参数
            params = {'sku_id':sku_id, 'count':count, 'csrfmiddlewaretoken':csrf}
            // 发起ajax post请求，访问/cart/add, 传递参数:sku_id count
            $.post('/cart/add', params, function (data) {
                if (data.res == 5){
                    // 添加成功
                    $(".add_jump").css({'left':$add_y+80,'top':$add_x+10,'display':'block'})
                    $(".add_jump").stop().animate({
                        'left': $to_y+7,
                        'top': $to_x+7},
                        "fast", function() {
                            $(".add_jump").fadeOut('fast',function(){
                                // 重新设置用户购物车中商品的条目数
                                $('#show_count').html(data.total_count);
                            });
                    });
                }
                else{
                    // 添加失败
                    alert(data.errmsg)
                }
            })
        })
    </script>
{% endblock bottomfiles %}

Movie_site/templates/index.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}MyMovieSite-HomePage{% endblock title %}
{% block topfiles %}
    <script type="text/javascript" src="{% static 'js/jquery-1.12.4.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/jquery-ui.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/slide.js' %}"></script>
{% endblock topfiles %}
{% block body %}
    <div class="navbar_con">
        <div class="navbar">
            <h1 class="fl">Groups</h1>
            <ul class="navlist fl">
                <li><a href="{% url 'group:join_group' %}">Join a group</a></li>
                <li class="interval">|</li>
                <li><a href="{% url 'group:create_group' %}">Create a group</a></li>
                <li class="interval">|</li>
                <li><a href="{% url 'group:unsubscribe' %}">Unsubscribe</a></li>
                <li class="interval">|</li>
                <li><a href="{% url 'group:event' %}">Event</a></li>
                <li class="interval">|</li>
                <li><a href="{% url 'movie:list' %}">Movie</a></li>
            </ul>
        </div>
    </div>

            {% for group in groups %}
              <div class="group">
                <h3><a href="{% url 'group:event' %}">{{group.group_name }}</a></h3>
              </div>
            {% empty %}
              <div class="group">
                  <h3>There is no group</h3>
              </div>
            {% endfor %}

{% endblock body %}

Movie_site/templates/join_group.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}MyMovieSite:Join{% endblock title %}
{% block topfiles %}
    <script type="text/javascript" src="{% static 'js/jquery-1.12.4.min.js' %}"></script>
{% endblock topfiles %}
{% block header_con %}{% endblock header_con %}
{% block search_bar %}{% endblock search_bar %}
{% block body %}
    <div class="register_con">
        <div class="l_con fl">
            <div class="reg_slogan">OOD TEAM 3</div>
            <div class="reg_banner"></div>
        </div>

        <div class="r_con fr">
            <div class="reg_title clearfix">
                <h1>Join a Group</h1>
                <a href="{% url 'group:index' %}">Back</a>
            </div>
            <div class="reg_form clearfix">
                <form method="post" action="/group/join_group/">
                    {% csrf_token %}
                <ul>

                    <li>
                        <label>Group:</label>
                        <input type="text" name="group_name" id="group_name">
                    </li>

                    <li class="reg_sub">
                        <input type="submit" value="Join" name="">
                    </li>
                </ul>
                </form>
                {{ errmsg }}
            </div>

        </div>

    </div>
{% endblock body %}

Movie_site/templates/login.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}MyMovieSite:Login{% endblock title %}
{% block header_con %}{% endblock header_con %}
{% block search_bar %}{% endblock search_bar %}
{% block body %}
    <div class="login_top clearfix">

    </div>

    <div class="login_form_bg">
        <div class="login_form_wrap clearfix">
            <div class="slogan fl">OOD TEAM3</div>
            <div class="login_form fr">
                <div class="login_title clearfix">
                    <h1>Login</h1>
                    <a href="#">SignUp</a>
                </div>
                <div class="form_input">
                    <form method="post">
                        {% csrf_token %}
                        <input type="text" name="username" class="name_input" value="{{ username }}" placeholder="Username">
                        <div class="user_error">error</div>
                        <input type="password" name="pwd" class="pass_input" placeholder="Password">
                        <div class="pwd_error">error</div>
                        <div class="more_input clearfix">
                            <input type="checkbox" name="remember" {{ checked }}>
                            <label>Remember me</label>
                            <a href="#">Forget password</a>
                        </div>
                        <input type="submit" name="" value="login" class="input_submit">
                    </form>
                </div>
            </div>
        </div>
    </div>
    {{ errmsg }}
{% endblock body %}

Movie_site/templates/pull_movie.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}MyMovieSite:Movie{% endblock title %}
{% block topfiles %}
    <script type="text/javascript" src="{% static 'js/jquery-1.12.4.min.js' %}"></script>
{% endblock topfiles %}
{% block header_con %}{% endblock header_con %}
{% block search_bar %}{% endblock search_bar %}
{% block body %}
    <div class="register_con">
        <div class="l_con fl">
            <div class="reg_slogan">OOD TEAM 3</div>
            <div class="reg_banner"></div>
        </div>

        <div class="r_con fr">
            <div class="reg_title clearfix">
                <h1>Add a Movie</h1>
                <a href="{% url 'movie:list' %}">Back</a>
            </div>
            <div class="reg_form clearfix">
                <form method="post" action="/movie/pull_movie/">
                    {% csrf_token %}
                <ul>
                    <li>
                        <label>Movie:</label>
                        <input type="text" name="movie_name" id="movie_name">
                    </li>
                    <li>
                        <label>Trailer:</label>
                        <input type="text" name="trailer_links" id="trailer_links">
                    </li>
                    <li>
                        <label>Review:</label>
                        <input type="text" name="review_links" id="review_links">
                    </li>

                    <li class="reg_sub">
                        <input type="submit" value="Add" name="">
                    </li>
                </ul>
                </form>
                {{ errmsg }}
            </div>

        </div>

    </div>
{% endblock body %}

Movie_site/templates/unsubscribe.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}MyMovieSite:Unsubscribe{% endblock title %}
{% block topfiles %}
    <script type="text/javascript" src="{% static 'js/jquery-1.12.4.min.js' %}"></script>
{% endblock topfiles %}
{% block header_con %}{% endblock header_con %}
{% block search_bar %}{% endblock search_bar %}
{% block body %}
    <div class="register_con">
        <div class="l_con fl">
            <div class="reg_slogan">OOD TEAM 3</div>
            <div class="reg_banner"></div>
        </div>

        <div class="r_con fr">
            <div class="reg_title clearfix">
                <h1>Unsubscribe a Group</h1>
                <a href="{% url 'group:index' %}">Back</a>
            </div>
            <div class="reg_form clearfix">
                <form method="post" action="/group/unsubscribe/">
                    {% csrf_token %}
                <ul>
                    <li>
                        <label>Group:</label>
                        <input type="text" name="group_name" id="group_name">
                    </li>

                    <li class="reg_sub">
                        <input type="submit" value="Unsubscribe" name="">
                    </li>
                </ul>
                </form>
                {{ errmsg }}
            </div>

        </div>

    </div>
{% endblock body %}

Movie_site/templates/vote.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}MyMovieSite-VotePage{% endblock title %}
{% block topfiles %}
    <script type="text/javascript" src="{% static 'js/jquery-1.12.4.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/jquery-ui.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/slide.js' %}"></script>
{% endblock topfiles %}
{% block body %}
    <div class="navbar_con">
        <div class="navbar">
            <h1 class="fl">Vote</h1>
            <ul class="navlist fl">
                <li><a href="{% url 'group:create_vote' %}">Create a Vote</a></li>
                <li class="interval">|</li>
                <li><a href="{% url 'group:event' %}">Event</a></li>
                <li class="interval">|</li>
                <li><a href="{% url 'group:vote_record' %}">Vote Record</a></li>
            </ul>
        </div>
    </div>




            {% for vote in votes %}
              <div class="vote">
                <h3><a href="{% url 'group:vote_detail' %}">{{vote.vote_name }}</a></h3>
              </div>
            {% empty %}
              <div class="votes">
                  <h3>There is no vote</h3>
              </div>
            {% endfor %}



{% endblock body %}

Movie_site/templates/vote_detail.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}MyMovieSite:Vote{% endblock title %}
{% block topfiles %}
    <script type="text/javascript" src="{% static 'js/jquery-1.12.4.min.js' %}"></script>
{% endblock topfiles %}
{% block header_con %}{% endblock header_con %}
{% block search_bar %}{% endblock search_bar %}
{% block body %}
    <div class="register_con">
        <div class="l_con fl">
            <div class="reg_slogan">OOD TEAM 3</div>
            <div class="reg_banner"></div>
        </div>

        <div class="r_con fr">
            <div class="reg_title clearfix">
                <h1>Vote Page</h1>
                <a href="{% url 'group:vote' %}">Back</a>
            </div>
            <div class="reg_form clearfix">
                <form method="post" action="/group/vote_detail/">
                    {% csrf_token %}
                <ul>
                    <li>
                        <label>Vote:</label>
                        <input type="text" name="vote_name" value="">
                    </li>
                     <h3>Please Input your vote results: yes or no</h3>
                     <input type="radio" name="vote_record", value=1><label>YES</label>
                     {# <input type="radio" name="vote_record", value="no"><label>NO</label> #}
                     <input type="radio" name="vote_record", value=0><label>NO</label>
                    <li class="reg_sub">
                        <input type="submit" value="Submit" name="">
                    </li>
                </ul>
                </form>
                {{ errmsg }}
            </div>

        </div>

    </div>
{% endblock body %}

Movie_site/templates/vote_record.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}MyMovieSite-Vote Record Page{% endblock title %}
{% block topfiles %}
    <script type="text/javascript" src="{% static 'js/jquery-1.12.4.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/jquery-ui.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/slide.js' %}"></script>
{% endblock topfiles %}
{% block body %}
    <div class="navbar_con">
        <div class="navbar">
            <h1 class="fl">Vote Record</h1>
            <ul class="navlist fl">
                <li><a href="{% url 'group:vote' %}">Vote</a></li>
            </ul>
        </div>
    </div>


    <div class="l_wrap fl clearfix">
          <div class="panel-body">

              <div class="record">
                  <h3><lable>Yes:</lable></lable><a href="{% url 'group:vote_record' %}">{{Yes}}</a> </h3>
                  <h3><lable>No:</lable></lable><a href="{% url 'group:vote_record' %}">{{No}}</a> </h3>
              </div>
          </div>
    </div>

{% endblock body %}